/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    AppLayout: typeof import('./src/components/layout/AppLayout.vue')['default']
    AppSidebar: typeof import('./src/components/layout/AppSidebar.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    JsonViewer: typeof import('./src/components/common/JsonViewer.vue')['default']
    RecordTable: typeof import('./src/components/common/RecordTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatisticCard: typeof import('./src/components/common/StatisticCard.vue')['default']
    StatusCard: typeof import('./src/components/common/StatusCard.vue')['default']
    StreamOutput: typeof import('./src/components/common/StreamOutput.vue')['default']
    TokenDisplay: typeof import('./src/components/common/TokenDisplay.vue')['default']
  }
}
